// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwZt7sw6jHDAgiHwnqnsr6ZTbj8hwNTZ0',
    appId: '1:81255207773:web:7ca395a0534b6666c30eb4',
    messagingSenderId: '81255207773',
    projectId: 'jenkins345',
    authDomain: 'jenkins345.firebaseapp.com',
    storageBucket: 'jenkins345.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4qpkYaWty8ped6uVx1JOYFrrAtsu9h1s',
    appId: '1:81255207773:android:c4665a67867eadaac30eb4',
    messagingSenderId: '81255207773',
    projectId: 'jenkins345',
    storageBucket: 'jenkins345.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvnOl9J_-DG5Zw--hs44VtN8AseYb7u0s',
    appId: '1:81255207773:ios:82f04d5535ff562fc30eb4',
    messagingSenderId: '81255207773',
    projectId: 'jenkins345',
    storageBucket: 'jenkins345.firebasestorage.app',
    iosBundleId: 'com.devesh.jenkinsd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvnOl9J_-DG5Zw--hs44VtN8AseYb7u0s',
    appId: '1:81255207773:ios:67fa3f897d1e0888c30eb4',
    messagingSenderId: '81255207773',
    projectId: 'jenkins345',
    storageBucket: 'jenkins345.firebasestorage.app',
    iosBundleId: 'com.example.jenkinTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwZt7sw6jHDAgiHwnqnsr6ZTbj8hwNTZ0',
    appId: '1:81255207773:web:2cf334e0a24f5e68c30eb4',
    messagingSenderId: '81255207773',
    projectId: 'jenkins345',
    authDomain: 'jenkins345.firebaseapp.com',
    storageBucket: 'jenkins345.firebasestorage.app',
  );

}